version: '3'

services:

  app:
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - yarn:/home/node/.cache/yarn
    tty: true
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
volumes:
  yarn:
